services:
  app:
    build:
      context: .
      target: code
    init: true
    ports: [ 3000:3000 ]
    environment:
      - "GO_CONN=host=gordian-db port=5432 user=alexander password=kopis dbname=budget sslmode=disable"
      - "CF_CONN=host=cashflow-db port=5432 user=cashflow password=cashflow dbname=cashflow sslmode=disable"
      - LOGIN_API_URL=http://login:7002
      - LOGIN_FRONTEND_URL=http://localhost:7002
      - PLS_URL=https://pls.datasektionen.se
      - PLS_SYSTEM=gordian
      - SERVER_PORT=3000
      - SERVER_URL=http://localhost:3000
      - LOGIN_TOKEN=schmunguss
    depends_on:
      gordian-db:
        condition: service_healthy
      cashflow-db:
        condition: service_healthy
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /src/
        - path: go.sum
          action: rebuild
    command: go run .
  gordian-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=budget
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=kopis
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d budget -U alexander'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
  cashflow-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=cashflow
      - POSTGRES_USER=cashflow
      - POSTGRES_PASSWORD=cashflow
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d cashflow -U cashflow'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
  login:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports: [ 7002:7002 ]
    environment:
      # le big admin moment, you can change this to the output of `curl https://dfunkt.datasektionen.se/api/role/kassor/current | jq '.mandates[0].User.kthid' -r`
      - KTH_ID=lukmal
