ARG GO_VERSION=1.26.4

FROM golang:${GO_VERSION}-alpine AS code

RUN apk add nginx

WORKDIR /src

COPY go.* ./
COPY . .

RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=cache,target=/root/.cache/go-build/ \
    go mod download -x

RUN echo "nginx &" >> run.sh
RUN echo "go run ." >> run.sh
RUN chmod +x run.sh

FROM code AS build


RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=cache,target=/root/.cache/go-build/ \
    CGO_ENABLED=0 go build -o /bin/server ./

FROM alpine:latest

COPY --from=build /bin/server /bin/
COPY --from=code /src/run.sh ./
CMD [ "./run.sh" ]
